import { describe, it } from "node:test";
import assert from "node:assert/strict";

import { DEMO_ART } from "../../site/demo-art.js";
import { fixture } from "../helpers.js";

/**
 * The demo gallery shows real artwork, generated by the contract and committed
 * to `site/demo-art.js` because browsers cannot compute keccak256.
 *
 * Committed generated data is a promise that decays. The moment `Art.sol`
 * changes, the page starts showing pictures no token has ever had, and nothing
 * says so. This is the check that makes the promise hold.
 */
describe("demo art", () => {
  it("matches what the contract draws today", async () => {
    const f = await fixture();

    for (const token of DEMO_ART) {
      await f.collection.write.mint([f.seller.account.address]);
    }

    for (const token of DEMO_ART) {
      const drawn = await f.collection.read.imageOf([BigInt(token.id)]);
      assert.equal(
        token.svg,
        drawn,
        `token ${token.id} in site/demo-art.js is stale. Re-run scripts/gen-demo-art.ts`,
      );
    }
  });

  it("states the royalty each token actually charges", async () => {
    const f = await fixture();

    for (const token of DEMO_ART) {
      await f.collection.write.mint([f.seller.account.address]);
    }

    for (const token of DEMO_ART) {
      const [, amount] = await f.collection.read.royaltyInfo([BigInt(token.id), 10_000n]);
      assert.equal(token.royalty, `${amount / 100n}.${(amount % 100n) / 10n}%`);
    }
  });

  it("carries enough tokens to fill a gallery", () => {
    assert.ok(DEMO_ART.length >= 8, "a marketplace with three items does not read as a marketplace");
    assert.deepEqual(
      DEMO_ART.map((t) => t.id),
      DEMO_ART.map((_, i) => i + 1),
      "ids must be sequential from 1, the way the contract mints them",
    );
  });
});
